name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2

      - uses: erlef/setup-elixir@v1
        with:
          otp-version: 23.3
          elixir-version: 1.11.4

      - name: Install Dependencies
        run: mix deps.get --only test

      - run: mix deps.compile
      - run: mix compile --warnings-as-errors
      - run: mix test
